import { Activity, Award, Flame, TrendingUp } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useFitness } from "../context/FitnessContext";
import { Card, PageHeading } from "../components/ui/Primitives";

export default function ProgressPage() {
  const { workouts, calories } = useFitness();
  const totalMinutes = workouts.reduce((total, workout) => total + Number(workout.minutes), 0);
  const chartData = workouts.slice().reverse().map((workout, index) => ({ day: `Log ${index + 1}`, minutes: workout.minutes, calories: Math.round(workout.minutes * 8) }));
  const hasData = chartData.length > 0;
  return <><PageHeading eyebrow="Progress analytics" title="Small actions, visible change." copy="Your charts begin building as soon as you log workouts and set your targets."/>
    <div className="progress-summary"><Card><span className="mini-icon green"><TrendingUp size={17}/></span><p>Weight trend</p><strong>—</strong><span className="up-text">Add check-ins to track</span></Card><Card><span className="mini-icon purple"><Flame size={17}/></span><p>Workout sessions</p><strong>{workouts.length}</strong><span className="up-text">Logged in your account</span></Card><Card><span className="mini-icon cyan"><Activity size={17}/></span><p>Total activity</p><strong>{totalMinutes} <small>min</small></strong><span className="up-text">Built from your logs</span></Card><Card><span className="mini-icon orange"><Award size={17}/></span><p>Daily calorie target</p><strong>{calories || "—"}{calories ? <small> kcal</small> : null}</strong><span className="up-text">Set it in Calories</span></Card></div>
    <div className="chart-grid"><Card className="chart-card"><div className="list-header"><div><h3>Workout duration</h3><p>Your session timeline appears here.</p></div></div>{hasData ? <div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="minutesGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#00f2fe" stopOpacity=".42"/><stop offset="100%" stopColor="#00f2fe" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.07)" vertical={false}/><XAxis dataKey="day" stroke="#aeb8cc" tickLine={false} axisLine={false}/><YAxis stroke="#aeb8cc" tickLine={false} axisLine={false}/><Tooltip contentStyle={{background:"#10172a",border:"1px solid rgba(103,232,249,.2)",borderRadius:"10px"}}/><Area type="monotone" dataKey="minutes" stroke="#00f2fe" strokeWidth={3} fill="url(#minutesGradient)"/></AreaChart></ResponsiveContainer></div> : <EmptyChart label="Log a workout to see your duration trend."/>}</Card>
      <Card className="chart-card"><div className="list-header"><div><h3>Training effort</h3><p>An estimated activity trend from your sessions.</p></div></div>{hasData ? <div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="effortGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#bd4bff" stopOpacity=".42"/><stop offset="100%" stopColor="#bd4bff" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.07)" vertical={false}/><XAxis dataKey="day" stroke="#aeb8cc" tickLine={false} axisLine={false}/><YAxis stroke="#aeb8cc" tickLine={false} axisLine={false}/><Tooltip contentStyle={{background:"#10172a",border:"1px solid rgba(189,75,255,.2)",borderRadius:"10px"}}/><Area type="monotone" dataKey="calories" stroke="#bd4bff" strokeWidth={3} fill="url(#effortGradient)"/></AreaChart></ResponsiveContainer></div> : <EmptyChart label="Your activity effort will appear after your first log."/>}</Card></div>
  </>;
}

function EmptyChart({ label }) { return <div className="chart-empty"><Activity/><p>{label}</p></div>; }
