import { Bot, CornerDownLeft, Sparkles, UserRound } from "lucide-react";
import { useState } from "react";
const suggestions = ["What's my recovery score?", "Generate a 20-min leg workout", "High protein meal plan under $10"];
const answers = {
  "What's my recovery score?": "Your readiness is 86/100 today. Sleep and hydration are both solid, so a moderate-to-hard lower body session is a good fit.",
  "Generate a 20-min leg workout": "Try this 20-minute leg circuit: 3 rounds of 12 goblet squats, 10 reverse lunges per side, 12 hip bridges and a 45-second wall sit. Rest 45 seconds between rounds.",
  "High protein meal plan under $10": "Build a bowl with 150g Greek yogurt, oats, banana and peanut butter for breakfast; chicken, rice and frozen vegetables for lunch; then eggs with whole-wheat toast for dinner. It lands near 120g protein for roughly $9–10 depending on your area.",
};
export default function ForgeAIChat() { const [messages,setMessages]=useState([{role:"ai",text:"I’m Sudesh AI. Tell me what you’re training for today, and I’ll help you make it count."}]); const [text,setText]=useState(""); const send=(value)=>{const question=value.trim();if(!question)return;setMessages(m=>[...m,{role:"user",text:question},{role:"ai",text:answers[question]||"That’s a strong question. For sustainable results, make the next session specific: choose one main movement, track the load, and finish with a protein-rich meal within a few hours."}]);setText("");}; return <div className="chat-shell"><div className="chat-head"><span className="icon-orb purple"><Bot size={20}/></span><div><h3>Sudesh AI</h3><p><i/> Online · responds instantly</p></div><Sparkles size={18}/></div><div className="chat-messages">{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><span>{m.role==="ai"?<Bot size={15}/>:<UserRound size={15}/>}</span><p>{m.text}</p></div>)}</div><div className="prompt-pills">{suggestions.map(s=><button key={s} onClick={()=>send(s)}>{s}</button>)}</div><form className="chat-input" onSubmit={(e)=>{e.preventDefault();send(text)}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask about training, nutrition or recovery…"/><button aria-label="Send message"><CornerDownLeft size={19}/></button></form></div>; }
